### PR TITLE
Send email with job offer rejection notification

### PR DESCRIPTION
**Pull request by wbachnik**
Solution for #2

### CODE REVIEW

**Comment by joncle** [comment]
I'm happy... we might need to work on the text for the subject line though... @malemburg - "Job entry rejected" seems a little blunt, but otherwise, we're all good - thanks @wbachnik !

If someone wouldn't mind giving it a further glance over in case I've missed anything, we can merge this and work on wording later.

**Comment by wbachnik** [comment]
Couldn't really come up with something more polite. Let me know if you want to change the title/message or just modify the file.

**Comment by malemburg** [comment]
On 12.05.2014 14:37, Wiktor Bachnik wrote:

> Couldn't really come up with something more polite. Let me know if you want to change the title/message or just modify the file.

I think "Job entry not accepted" is more polite :-)

To put things more into context, it may make sense extending
this a bit to:

"Python Job Board entry not accepted"

## 

Marc-Andre Lemburg

**Comment by joncle** [comment]
How about we prefix the emails so it's identifiable, something like: `Python Job Board:`, then follow it up with
- The position for {{ job_title}} has now been listed.
- The position for {{ job_title }} has not been accepted - please see details.

Something like those anyway?

**Comment by malemburg** [comment]
On 12.05.2014 15:16, Jon Clements wrote:

> How about we prefix the emails so it's identifiable, something like: `Python Job Board:`, then follow it up with
> - The position for {{ job_title}} has now been listed.
> - The position for {{ job_title }} has not been accepted - please see details.
> 
> Something like those anyway?

Even better :-)

## 

Marc-Andre Lemburg

**Comment by joncle** [comment]
Ugh - quickly running out of time again... @wbachnik do we have the `job_title` available to the context to do this?

**Comment by joncle** [comment]
Merging this: see #12 for discussion on subject lines

**Comment by wbachnik** [comment]
@joncle currently it's not passed to the context, but that can be easily fixed in the [mail sending helper](https://github.com/python-jobs-board/pythondotorg/blob/generate-rejection-email/jobs/listeners.py#L47) as it has access to full `Job` object. Just let me know what's the decision regarding templates.

**Pull request merged**
