### PR TITLE
Send email with job approval notification

### LINKED ISSUE #1: Generate an approval email whenever a job entry is changed to "approved"
Here's an email template:
"""
Dear {{name}},

Thank you for choosing to list your vacancy on python.org's Job Board.

Your listing is now active and is available to view at {{ job_link }}. If
you notice any errors in the listing, please notify the Job Board team as
soon as possible.

To keep the job board fresh and active for job seekers, we'd appreciate if
you'd let us know as soon as possible when the position is filled so we can
remove your listing.

Good luck in filling your position,

{{ review_name }}
Python Job Board

PS: Please consider a donation to the non-profit Python Software Foundation
(PSF) which runs the Python Job Board, directly supports Python and helps
build the community of Python programmers. Donations are tax-deductible
in the US. For more details or to donate, go to:

http://python.org/psf/donations/
"""

### PR DESCRIPTION
**Pull request by wbachnik**
Fixes #1

### CODE REVIEW

**Comment by wbachnik** [comment]
I updated the PR with fixes suggested by @LuRsT.
I also added email message and subject templates, I forgot to commit them previously.

**Comment by joncle** [comment]
Good job @wbachnik.

The main concern is we should really have something in https://github.com/python-jobs-board/pythondotorg/blob/master/jobs/tests/test_models.py#L27 to test `approve` correctly `signals` and an email is sent with the correct information (you can use something similar to https://github.com/python-jobs-board/pythondotorg/blob/master/jobs/tests/test_views.py#L365 which uses `mail.outbox` in the testing). If that could be done and the same for rejections, then #2 can be more easily tested.

Minor asides:
- I'm not sure the email subject needs to really be from a template, but not overly worried about it at the moment. Seems just easier to keep it built inline at that point as someone's going to have to commit changes to the server anyway to amend it.
- We may wish to generate an HTML version of the email similar to how the comment thing works, but I'm not sure about that either.

**Comment by wbachnik** [comment]
Jon,

I was thinking about testing that as well -- we can test signals using [mock-django](https://github.com/dcramer/mock-django) but was hesitant of introducing another dependency. Anyway, that will be a good thing to do, so I'll just do that.

Regarding  subject template -- IMO it's more convenient to have it in the template, it also provides more consistency: you don't have to look into two places when needing to change something about the email message. If you feel it's better to hard code it, it's not a problem.

Regarding HTML messages: That would be an easy extension, we'd just need to create a HTML-based email template and switch to using `EmailMultiAlternatives`, as  described in [Django docs](https://docs.djangoproject.com/en/1.6/topics/email/#sending-alternative-content-types).

**Comment by joncle** [comment]
Wiktor,

I wouldn't say we need to necessarily test the signal itself. How the system decides it needs to use `send_mail` isn't as important as that it does with reasonable content being output. I'm completely open to suggestions on this but I _think_ we can get away with just `test_approved_manager` and `test_rejected_manager` checking `django.core.mail.outbox` that something is present with expected content as a not unreasonable starting point.

Let's ignore the subject template and the HTML for now and focus on just getting #1 and #2 sorted with suitable tests.

**Comment by wbachnik** [comment]
I updated tests to check for approval email being sent.

**Pull request merged**
