### PR TITLE
Fix form field validation errors display

### PR DESCRIPTION
**Pull request by wbachnik**
Only a simple CSS change this time.

### CODE REVIEW

**Comment by LuRsT** [comment]
Looks good, although the fact that you had to change two scss files makes me a sad panda :panda_face:

**Comment by wbachnik** [comment]
Those are actually raw .css files, and I couldn't find a scss sources for them anywhere. A bit strange if you ask me.

**Comment by LuRsT** [comment]
Oh right, my bad, I'm used to seeing scss files :P.

Maybe later we can start using scss instead of css.

**Comment by joncle** [comment]
Guys.... Just need to be slightly wary as the styling is generated via compass so an automated run could over-write the changes made here if made elsewhere in the code branch...

**Comment by wbachnik** [comment]
Thanks Jon, that's actually what I thought. And now I found it (static/sass/_layout.scss). Will update in few minutes.

**Comment by LuRsT** [comment]
Awkward, but at least now we know, sorry about that!

**Comment by wbachnik** [comment]
That's actually due to my lack of experience with frontend stuff. At least I learned where to look :-)
New PR with changes made to the scss source: https://github.com/python-jobs-board/pythondotorg/pull/10

**Comment by wbachnik** [comment]
BTW @joncle how is the process of generating css managed? I can see that compass is configured to output css into 'stylesheets' directory, are the generated files moved back to 'sass' directory by hand?

**Comment by joncle** [comment]
My understanding is that compass is run each time on a new deploy to the
production server and will over-write the CSS files which are then served
statically from that point forth... No moving is actually involved as the
sass remains in the same place.

**Pull request merged**
